//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM_Monitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_INCIDENT_202601_202606
    {
        public string incidentid { get; set; }
        public string ticket_number { get; set; }
        public string creation_date { get; set; }
        public string modification_date { get; set; }
        public string user_creation { get; set; }
        public string user_modification { get; set; }
        public string statecode { get; set; }
        public string statuscode { get; set; }
        public Nullable<int> caseorigincode { get; set; }
        public string contratsouscrit_incidentname { get; set; }
        public string encoded_contratsouscrit_incidentname { get; set; }
        public string contratsouscrit_incident { get; set; }
        public string msisdn_concerne { get; set; }
        public string encoded_msisdn_concerne { get; set; }
        public string id_type_reclamation { get; set; }
        public string contactid { get; set; }
        public string contractid { get; set; }
        public string accountid { get; set; }
        public string otn_indicateur_satisfaction { get; set; }
        public string queueid { get; set; }
        public string comptefacturation_contrat { get; set; }
        public string date_cloture { get; set; }
        public string date_rejet { get; set; }
        public Nullable<int> msisdn { get; set; }
        public string encoded_msisdn { get; set; }
        public Nullable<int> delai_traitement { get; set; }
        public Nullable<int> tmcode { get; set; }
        public Nullable<byte> prgcode { get; set; }
        public Nullable<System.DateTime> entry_date_crm { get; set; }
        public string subject_name { get; set; }
        public string parent_subject_name { get; set; }
        public string statecode_value { get; set; }
        public string statuscode_value { get; set; }
        public string rnk { get; set; }
        public string description { get; set; }
    }
}
